server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signer: "e/CsXqXdiRtaEvb2zPwkhCEY4SMT8W3DY78nqmR/7Vl/3pOmK0YWSkOmMPi5dHNK"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in second
